### ISSUE TITLE
Failed to load. Cannot read properties of null (reading 'nextBatch')

### ISSUE THREAD

**Issue by xobs** [cinnyapp/cinny-desktop#331]
### Describe the bug

When starting up Cinny, it presents a window that says "Failed to load. Cannot read properties of null (reading 'nextBatch')". There is a `Retry` button that causes the message box to disappear and reappear again immediately.

![image](https://github.com/user-attachments/assets/6ae56dd6-fe60-478d-acbc-20939b8af369)

### Reproduction

1. Open Cinny

### Expected behavior

Cinny should startup

### Platform and versions

```shell
1. OS: Windows 11
2. Cinny version: I think it's the latest -- it just updated, but I can't tell how to get the version number
3. Matrix homeserver. matrix.im
4. Downloaded from: Clicking "Yes" when it asked me to upgrade. Originally was downloaded from Github releases
```

**Comment by kfiven** [comment]
Hi, Could you please Right click > Inspect > Console for any error?

**Comment by xobs** [comment]
Sure. It says:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextBatch')
    at index-Pm8eP4Ep.js:79946:47254
    at async index-Pm8eP4Ep.js:79946:46975
    at async buA (index-Pm8eP4Ep.js:79949:106225)
    at async index-Pm8eP4Ep.js:9:62957
```

**Comment by kfiven** [comment]
In the console, could you go to Application and try clearing "Local storage" and deleting "IndexedDB" entries.

Seems like you also had this in 3.2.1 as reported in https://github.com/cinnyapp/cinny/issues/1764

**Comment by xobs** [comment]
Yes, like before, that works around the issue. The error is different, so it didn't show up when I searched for fixes.

That means the underlying problem is still there.

**Comment by kfiven** [comment]
well, underlying problem is not known, and that is what I am trying to find. Did clearing those storage fix the issue? Because I have cinny working well on windows. Seems there are something specific happening for you.

**Comment by xobs** [comment]
Yes, clearning storage (by going to Application, then Storage on the left, then "Clear site data" on the right) fixed it so that it now starts up and lets me log in.

**Comment by kfiven** [comment]
This probably seems like similar to https://github.com/element-hq/element-web/issues/27520
